/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ElixirService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "LimeLeaseVPC": {
      "type": "sst.aws.Vpc"
    }
    "NextjsApp": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "OccupieVPC": {
      "type": "sst.aws.Vpc"
    }
    "Postgresql": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "Services": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Storage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}