query myTeam($first: Int!, $after: String, $before: String, $last: Int, $searchTerm: String) {
  myTeam(first: $first, after: $after, before: $before, last: $last, searchTerm: $searchTerm) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    edges {
      cursor
      node {
        ...AgencyAgentBase
        properties {
          id
          address {
            unitNumber
            streetName
            streetType
            streetNumber
            suburb
            postcode
            state
          }
        }
      }
    }
  }
}
