AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ScrapeApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "ScrapeApi"
      StageName: "prod"
      Auth:
        ApiKeyRequired: true
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
        AllowOrigin: "'*'"
        
  ScrapeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 1024
      Timeout: 200
      ReservedConcurrentExecutions: 100
      Events:
        ScrapeEvent:
          Type: Api
          Properties:
            Path: /scrape
            Method: post
            RestApiId: !Ref ScrapeApi

Outputs:
  ApiEndpointUrl:
    Description: "URL of the API endpoint"
    Value: 
      !Sub "https://${ScrapeApi}.execute-api.${AWS::Region}.amazonaws.com/prod/scrape"