{application,exile,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,crypto]},
              {description,"NIF based solution to interact with external programs with back-pressure"},
              {modules,['Elixir.Collectable.Exile.Stream.Sink',
                        'Elixir.Enumerable.Exile.Stream','Elixir.Exile',
                        'Elixir.Exile.Process','Elixir.Exile.Process.Error',
                        'Elixir.Exile.Process.Exec',
                        'Elixir.Exile.Process.Nif',
                        'Elixir.Exile.Process.Operations',
                        'Elixir.Exile.Process.Pipe',
                        'Elixir.Exile.Process.State','Elixir.Exile.Stream',
                        'Elixir.Exile.Stream.AbnormalExit',
                        'Elixir.Exile.Stream.Sink','Elixir.Exile.Watcher']},
              {registered,[]},
              {vsn,"0.8.0"},
              {mod,{'Elixir.Exile',[]}}]}.
