{application,jsonrs,
             [{compile_env,[{rustler_precompiled,[force_build,jsonrs],error}]},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,rustler_precompiled]},
              {description,"A fully-featured and performant JSON library powered by Rust\n"},
              {modules,['Elixir.Jsonrs','Elixir.Jsonrs.Encoder',
                        'Elixir.Jsonrs.Encoder.Any',
                        'Elixir.Jsonrs.Encoder.Date',
                        'Elixir.Jsonrs.Encoder.DateTime',
                        'Elixir.Jsonrs.Encoder.List',
                        'Elixir.Jsonrs.Encoder.Map',
                        'Elixir.Jsonrs.Encoder.NaiveDateTime',
                        'Elixir.Jsonrs.Encoder.Time',
                        'Elixir.Jsonrs.Encoder.Tuple',
                        'Elixir.Jsonrs.Encoder.URI']},
              {registered,[]},
              {vsn,"0.3.3"}]}.
