import { User } from '@graphql/generated';
import { Maybe } from '@types/Maybe';
import { motion } from 'framer-motion';
import Image from 'next/image';
import styled from 'styled-components';

import systemIcon from '@public/images/limelease-icon-dark.png';
import { Colours } from '@utils/Colours';
import { dayjs } from '@utils/DayjsTimezone';
import { DEVICE_TIMEZONE } from '@utils/Constants';
import { useContext, useEffect, useMemo } from 'react';
import useElementOnScreen from '@hooks/useElementOnScreen';
import { RequestDetailsContext } from '../containers/RequestDetailsContainer';
import { Tooltip } from 'antd';
import { cardAnimationProps, fadeInOutProps } from '@utils/AnimationsProps';

interface RequestDetailCommentProps {
  index: number;
  insertDate: Maybe<string>;
  authorName: Maybe<string>;
  messageBody: Maybe<string>;
  systemGenerated: Maybe<boolean>;
  onTopCommentVisibilityChanged: (visible: boolean) => void;
}

const RequestDetailComment: React.FC<RequestDetailCommentProps> = ({
  index,
  insertDate,
  authorName,
  messageBody,
  systemGenerated = false,
  onTopCommentVisibilityChanged,
}) => {
  const dayjsInsertDate = useMemo(() => dayjs(insertDate).tz(DEVICE_TIMEZONE), [insertDate]);

  const formattedDate = useMemo(() => {
    const now = dayjs();
    const twoDaysAgo = now.subtract(1, 'day');

    if (dayjsInsertDate.isAfter(twoDaysAgo)) {
      return dayjsInsertDate.fromNow();
    } else {
      return dayjsInsertDate.format('DD/MM/YYYY hh:mma');
    }
  }, [dayjsInsertDate]);

  const bodySplit = useMemo(() => messageBody?.split(/(@\w+)/g), [messageBody]);

  const [ref, isVisible] = useElementOnScreen({
    root: null,
    rootMargin: '0px',
    threshold: 0.1,
  });

  useEffect(() => {
    onTopCommentVisibilityChanged(isVisible);
  }, [isVisible]);

  return (
    <CommentContainer layout {...cardAnimationProps} systemGenerated={systemGenerated} ref={index === 0 ? ref : null}>
      <AuthorDetailsRow>
        <AuthorName>{authorName}</AuthorName>
        <CommentDetailsRow>
          <CommentDate isHighlighted={dayjs().diff(dayjsInsertDate, 'hours') <= 8}>
            <Tooltip title={dayjsInsertDate.format('DD/MM/YYYY hh:mma')}>{formattedDate}</Tooltip>
          </CommentDate>
        </CommentDetailsRow>
      </AuthorDetailsRow>

      <CommentBodyContainer>
        <CommentBody>{bodySplit}</CommentBody>
      </CommentBodyContainer>

      {systemGenerated && (
        <GeneratedContainer>
          <Image src={systemIcon} width={16} height={16} />
          <GeneratedText>Generated by OccuPie</GeneratedText>
        </GeneratedContainer>
      )}
    </CommentContainer>
  );
};

const CommentDetailsRow = styled.div`
  display: flex;
`;

const GeneratedContainer = styled.div`
  display: flex;
  margin-top: 16px;
  align-items: center;
`;

const GeneratedText = styled.div`
  font-size: 12px;
  font-weight: 600;
  margin-left: 8px;
`;

const CommentContainer = styled(motion.div)<{ systemGenerated: boolean }>`
  border-radius: 10px;
  background: #fafafa;
  padding: 16px;
  margin-bottom: 24px;
  position: relative;
  ${(props) => props.systemGenerated && `background: #f0f0f0;`}
`;

const AuthorDetailsRow = styled.div`
  display: flex;
  align-items: center;
`;

const CommentDate = styled.div<{ isHighlighted: boolean }>`
  color: #8c8c8c;
  font-size: 12px;
  font-style: normal;
  font-weight: 500;
  line-height: 20px;
  ${(props) => props.isHighlighted && `color: ${Colours.LIME_5};`}
`;

const AuthorName = styled.div`
  color: #262626;
  font-size: 16px;
  font-style: normal;
  font-weight: 500;
  line-height: 24px;
  margin-right: 8px;
`;

const CommentBodyContainer = styled.div`
  margin-top: 8px;
`;

const CommentBody = styled.div`
  color: #595959;
  font-size: 16px;
  font-style: normal;
  font-weight: 500;
  line-height: 24px;
`;

export default RequestDetailComment;
