import Config

# Configure your database
config :lime_lease, LimeLease.Repo,
  username: "postgres",
  password: "",
  hostname: "localhost",
  database: "lime_lease_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 30

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :lime_lease, LimeLeaseWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "REDACTED_DEV_SECRET_KEY",
  watchers: [
    # Start the esbuild watcher by calling Esbuild.install_and_run(:default, args)
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :lime_lease, LimeLeaseWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/lime_lease_web/(live|views)/.*(ex)$",
      ~r"lib/lime_lease_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :lime_lease,
  clicksend_api_username: System.get_env("CLICKSEND_API_USERNAME") || "your_clicksend_username",
  clicksend_api_key: System.get_env("CLICKSEND_API_KEY") || "your_clicksend_api_key",
  front_end_url: System.get_env("FRONT_END_URL") || "http://localhost:3000"

config :lime_lease, LimeLease.Guardian,
  issuer: "limelease",
  secret_key: System.get_env("GUARDIAN_SECRET_KEY") || "your_guardian_secret_key_min_64_chars"

config :ex_aws,
  access_key_id: System.get_env("AWS_ACCESS_KEY_ID") || "your_aws_access_key_id",
  secret_access_key: System.get_env("AWS_SECRET_ACCESS_KEY") || "your_aws_secret_access_key",
  region: System.get_env("AWS_REGION") || "ap-southeast-2",
  bucket: System.get_env("AWS_BUCKET") || "limelease",
  static_folder: System.get_env("AWS_STATIC_FOLDER") || "static-files",
  api_gateway_endpoint: System.get_env("API_GATEWAY_ENDPOINT") || "https://your-api-gateway-endpoint"

config :lime_lease, LimeLease.Mailer,
  adapter: Swoosh.Adapters.Postmark,
  api_key: System.get_env("POSTMARK_API_KEY") || "your_postmark_api_key"

config :honeybadger,
  environment_name: :dev
