name: CI

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
#2
env:
  REGISTRY: "registry.digitalocean.com/limelease"
  ELIXIR_IMAGE_NAME: "elixir-api"
  WEB_IMAGE_NAME: "nextjs-app"

#3
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --use --name builder

        # Build and push Elixir API image
      - name: Build Elixir API container image
        run: |
          docker buildx build --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache-new -f ./limelease/services/elixir-api/Dockerfile -t $REGISTRY/$ELIXIR_IMAGE_NAME:latest ./limelease/services/elixir-api
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # Build and push Next.js web app image
      - name: Build Next.js web app container image
        run: |
          docker buildx build --cache-from type=local,src=/tmp/.buildx-cache --cache-to type=local,dest=/tmp/.buildx-cache-new -f ./limelease/apps/nextjs-app/Dockerfile -t $REGISTRY/$WEB_IMAGE_NAME:latest ./limelease/apps/nextjs-app
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
        
      - name: Remove all old images
        run: |
          IMAGE_NAME=$REGISTRY/$WEB_IMAGE_NAME
          if [ ! -z "$(doctl registry repository list | grep "$(echo $IMAGE_NAME)")" ]; then
            TAGS=$(doctl registry repository list-tags $(echo $IMAGE_NAME) --format Tag --no-header | grep -o "sha.*")
            for TAG in $TAGS; do
              doctl registry repository delete-manifest $(echo $IMAGE_NAME) $TAG --force
            done
          else
            echo "No repository"
          fi

      - name: Push Next.js web app image to DigitalOcean Container Registry
        run: docker push $REGISTRY/$WEB_IMAGE_NAME:latest

      - name: Push Elixir API image to DigitalOcean Container Registry
        run: docker push $REGISTRY/$ELIXIR_IMAGE_NAME:latest

      - name: Run registry garbage collection
        run: doctl registry garbage-collection start --include-untagged-manifests --force
        
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: fifsky/ssh-action@v0.0.6
        with:
          host: ${{ secrets.HOST }}
          user: root
          key: ${{ secrets.SSHKEY }}
          command: |
            # Login to registry
            docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} registry.digitalocean.com
            cd ~/apps/web
            docker compose pull
            docker compose down && docker compose up -d
            cd ~/apps/api
            docker compose pull
            docker compose down && docker compose up -d
